---
- name: create configuration directory
  become: yes
  file:
    path: /opt/runnable/consul
    state: directory
    recurse: yes

- name: create server tls certificate directory
  become: yes
  file:
    path: /opt/consul/server
    state: directory
    recurse: yes

- name: copy vault config
  become: yes
  template:
    src: consul.json.j2
    dest: /opt/runnable/consul/consul.json
