api_number_of_containers: 1
api_aws_access_key_id: ${AWS_ACCESS_KEY}
api_aws_secret_access_key: ${AWS_SECRET_KEY}
api_github_client_id: ${GITHUB_APPLICATION_CLIENT_ID}
api_github_client_secret: ${GITHBUB_APPLICATION_CLIENT_SECRET}
api_github_deploy_keys_bucket: runnable.deploykeys.${ENV}
api_mongo_auth: ${MONGO_USERNAME}:${MONGO_PASSWORD}
api_mongo_database: api
api_github_deploy_key_title: Runnable-io-${ENV}
api_mongo_replset_name: ${ENV}-rs0
api_s3_context_bucket: runnable.context.resources.${ENV}
api_s3_log_bucket: ${ENV}.container-logs
api_hostname: api.{{ domain }}
api_url: https://{{ api_hostname }}
api_socket_server_hostname: apisock.{{ domain }}
sendgrid_key: ${SENDGRID_KEY}
api_port: 80

krain_port: 3100

detention_host_address: "{{ hostvars[groups['detention'][0]]['ansible_default_ipv4']['address'] }}"
detention_hostname: detention.{{ domain }}
detention_port: 9123

big_poppa_host_address: "{{ hostvars[groups['big-poppa'][0]]['ansible_default_ipv4']['address'] }}"
big_poppa_pg_pass: ${POSTGRES_PASSWORD}
big_poppa_pg_host: ${ENV}.cnksgdqarobf.${AWS_REGION}.rds.amazonaws.com:5432
big_poppa_pg_port: 5432
big_poppa_pg_user: ${POSTGRES_PASSORD}
big_poppa_pg_database: big_poppa
big_poppa_github_token: ${GITHUB_TOKEN}
big_poppa_mongo_auth: ${MONGO_USERNAME}:${MONGO_PASSWORD}
big_poppa_mongo_replset_name: ${ENV}-rs0
big_poppa_pg_pool_min: 10
big_poppa_pg_pool_max: 20
big_poppa_port: 7788
big_poppa_intercom_key: ${INTERCOM_KEY}
big_poppa_intercom_id: ${INTERCOM_ID}

cream_host_address: "{{ hostvars[groups['cream'][0]]['ansible_default_ipv4']['address'] }}"
cream_hello_runnable_github_token: ${HELLO_RUNNABLE_GITHUB_TOKEN}
cream_stripe_secret_key: sk_test_4De8Zdkfcyb29swkMmjZUMRh
cream_stripe_publishable_key: pk_test_sHr5tQaPtgwiE2cpW6dQkzi8
cream_port: 8899

charon_port: 53

drake_hostname: drake.{{ domain }}
drake_port: 80

khronos_mongo_auth: ${MONGO_USERNAME}:${MONGO_PASSWORD}
khronos_mongo_replset_name: ${ENV}

navi_host_address: "{{ hostvars[groups['navi'][0]]['ansible_default_ipv4']['address'] }}"
navi_http_port: 3567
navi_cookie_secret: ${NAVI_SECRET}
navi_proxy_port: 65100
navi_proxy_ssl_port: 65101
navi_mongo_database: navi
navi_mongo_auth: ${MONGO_USERNAME}:${MONGO_PASSWORD}

link_hello_runnable_github_token: ${HELLO_RUNNABLE_GITHUB_TOKEN}

optimus_hostname: optimus.{{ domain }}
optimus_aws_access_id: ${AWS_ACCESS_KEY}
optimus_aws_secret_id: ${AWS_SECRET_KEY}
optimus_github_deploy_keys_bucket: runnable.deploykeys.${ENV}
optimus_port: 80

pheidi_mongo_auth: ${MONGO_USERNAME}:${MONGO_PASSWORD}
pheidi_mongo_replset_name: api
pheidi_runnabot_tokens: ${GITHUB_TOKEN}
pheidi_email_github_token: ${GITHUB_TOKEN}

registry_s3_access_key: ${AWS_ACCESS_KEY}
registry_s3_secret_key: ${AWS_SECRET_KEY}
registry_s3_bucket: runnableimages.${ENV}
registry_s3_region: ${AWS_REGION}

signin_frontend_s3_region: ${AWS_REGION}
web_url: https://app.{{ domain }}
marketing_url: https://{{ domain }}
mixpanel_url: https://mixpanel.{{ domain }}
web_aws_bucket_region: ${AWS_REGION}

aws_access_key_id: ${AWS_ACCESS_KEY}
aws_secret_access_key: ${AWS_SECRET_KEY}
shiva_aws_region: ${AWS_REGION}
shiva_dock_security_groups: ${AWS_DOCK_SECURITY_GROUP}
shiva_ssh_key_name: ${MAIN_HOST_ACCESS_KEY}
shiva_aws_instance_image_id: ami-30c74e50
shiva_aws_instance_image_name: dock-ami-build-v.0.0.1
shiva_aws_instance_type: t2.medium
shiva_dock_pool_asg_name: ${ENV}-asg-dock-pool
shiva_aws_launch_configuration_name: ${ENV}-dock-lc-0.0.1
shiva_aws_auto_scaling_group_subnets: ${AWS_DOCK_SUBNET}
shiva_aws_auto_scaling_group_max: 29
shiva_aws_auto_scaling_group_prefix: asg-${ENV}-

aws_access_key: ${AWS_ACCESS_KEY}
aws_secret_key: ${AWS_SECRET_KEY}
environment_name: ${ENV}

consul_host_address: "{{ hostvars[groups['consul'][0]]['ansible_default_ipv4']['address'] }}"
consul_https_port: 65201
consul_api_port: 65201

vault_hello_runnable_github_token: ${HELLO_RUNNABLE_GITHUB_TOKEN}
vault_aws_access_key_id: ${AWS_ACCESS_KEY}
vault_aws_secret_key: ${AWS_SECRET_KEY}
vault_aws_region: ${AWS_REGION}
vault_port: 65240
vault_ssl_port: 65241

stop_time: 5
log_driver: syslog
log_facility: local7
app_log_dir: /docker/app-logs

pg_user: ${POSTGRES_PASSORD}
pg_pass: ${POSTGRES_PASSWORD}
pg_host: ${POSTGRES_HOST}:5432
pg_database: astral

rabbit_username: ${RABBIT_USERNAME}
rabbit_password: ${RABBIT_PASSWORD}
rabbit_host_address: "{{ hostvars[groups['rabbitmq'][0]]['ansible_default_ipv4']['address'] }}"
rabbit_port: 54321

redis_host_address: "{{ hostvars[groups['redis'][0]]['ansible_default_ipv4']['address'] }}"
redis_port: 65251

swarm_master_port: 65250
swarm_host_address: "{{ hostvars[groups['swarm-manager'][0]]['ansible_default_ipv4']['address'] }}"
swarm_container_name: swarm
swarm_version: v1.2.3-0

docker_ca_path: /etc/ssl/docker/ca.pem
docker_key_path: /etc/ssl/docker/key.pem
docker_cert_path: /etc/ssl/docker/cert.pem
docker_port: 4242

mongo_port: 27017
mongo_hosts: "{% for host in groups['mongodb'] %}{{ hostvars[host]['ansible_default_ipv4']['address'] }}:{{ mongo_port }}{% if not loop.last %},{% endif %}{% endfor %}"

github_varnish_host: "{{ hostvars[groups['github-varnish'][0]]['ansible_default_ipv4']['address'] }}"
github_varnish_port: 8765
github_domain: api.github.com
is_github_enterprise: false
github_protocol: https
github_api_url: https://api.github.com

domain: ${DOMAIN}
node_env: ${ENV}
registry_port: 65001
user_content_domain: ${USER_CONTENT_DOMAIN}
max_navi_port: 65000
redis_tls_port: 65076
api_hello_runnable_github_token: ${HELLO_RUNNABLE_GITHUB_TOKEN}
vault_auth_token: ${VAULT_AUTH_TOKEN}
vault_token_01: ${VAULT_TOKEN_1}
vault_token_02: ${VAULT_TOKEN_2}
vault_token_03: ${VAULT_TOKEN_3}
vault_token_04: ${VAULT_TOKEN_2}
vault_token_05: ${VAULT_TOKEN_2}
proxy_container_image: runnable/sticky-nginx
proxy_container_image_version: v1.8.1
