## Custom Vars
# Make sure you include variables in main-vars.yml (from main-vars.yml)

## Defaults
is_on_prem: true

api_number_of_containers: 1
api_aws_access_key_id: "{{ aws_access_key_id }}"
api_aws_secret_access_key: "{{ aws_secret_access_key }}"
api_github_client_id: "{{ github_client_id }}"
api_github_client_secret: "{{ github_client_secret }}"
api_github_deploy_keys_bucket: "runnable.deploykeys.{{ environment }}"
api_mongo_auth: "{{ mongo_user }}:{{ mongo_password }}"
api_mongo_database: api
api_github_deploy_key_title: Runnable-io-{{ environment }}
api_s3_context_bucket: runnable.context.resources.{{ environment }}
api_s3_log_bucket: "{{ environment }}.container-logs"
api_hostname: api.{{ domain }}
api_url: https://{{ api_hostname }}
api_socket_server_hostname: apisock.{{ domain }}
api_port: 80

krain_port: 3100

detention_host_address: "{{ hostvars[groups['detention'][0]]['ansible_default_ipv4']['address'] }}"
detention_hostname: detention.{{ domain }}
detention_port: 9123

big_poppa_host_address: "{{ hostvars[groups['big-poppa'][0]]['ansible_default_ipv4']['address'] }}"
big_poppa_pg_pass: "{{ postgres_password }}"
big_poppa_pg_host: "{{ postgres_host }}"
big_poppa_pg_port: 5432
big_poppa_pg_user: "{{ postgres_user }}"
big_poppa_pg_database: big_poppa
big_poppa_github_token: "{{ github_token }}"
big_poppa_mongo_auth: "{{ mongo_user }}:{{ mongo_password }}"
big_poppa_pg_pool_min: 10
big_poppa_pg_pool_max: 20
big_poppa_port: 7788
big_poppa_intercom_key: "{{ intercom_key }}"
big_poppa_intercom_id: "{{ intercom_id }}"

cream_host_address: "{{ hostvars[groups['cream'][0]]['ansible_default_ipv4']['address'] }}"
cream_hello_runnable_github_token: "{{ hello_runnable_github_token }}"
cream_stripe_secret_key: sk_test_4De8Zdkfcyb29swkMmjZUMRh
cream_stripe_publishable_key: pk_test_sHr5tQaPtgwiE2cpW6dQkzi8
cream_port: 8899

charon_port: 53

clio_host_address: "{{ hostvars[groups['clio'][0]]['ansible_default_ipv4']['address'] }}"
clio_port: 8008
clio_mongo_auth: "{{ mongo_user }}:{{ mongo_password }}"
clio_mongo_database: clio

drake_hostname: drake.{{ domain }}
drake_port: 80

khronos_mongo_auth: "{{ mongo_user }}:{{ mongo_password }}"

navi_host_address: "{{ hostvars[groups['navi'][0]]['ansible_default_ipv4']['address'] }}"
navi_http_port: 3567
navi_proxy_port: 65100
navi_proxy_ssl_port: 65101
navi_mongo_database: navi
navi_mongo_auth: "{{ mongo_user }}:{{ mongo_password }}"

link_hello_runnable_github_token: "{{ hello_runnable_github_token }}"

optimus_hostname: optimus.{{ domain }}
optimus_aws_access_id: "{{ aws_access_key_id }}"
optimus_aws_secret_id: "{{ aws_secret_access_key }}"
optimus_github_deploy_keys_bucket: runnable.deploykeys.{{ environment }}
optimus_port: 80

pheidi_mongo_auth: "{{ mongo_user }}:{{ mongo_password }}"
pheidi_runnabot_tokens: "{{ github_token }}"
pheidi_email_github_token: "{{ github_token }}"

registry_host: "quay.io"
registry_s3_access_key: "{{ aws_access_key_id }}"
registry_s3_secret_key: "{{ aws_secret_access_key }}"
registry_s3_bucket: runnableimages.{{ environment }}
registry_s3_region: "{{ aws_region }}"

signin_frontend_s3_region: "{{ aws_region }}"
web_url: https://app.{{ domain }}
web_aws_bucket_region: "{{ aws_region }}"
marketing_url: https://{{ domain }}
mixpanel_url: https://mixpanel.{{ domain }}

shiva_aws_region: "{{ aws_region }}"
shiva_dock_security_groups: "{{ aws_dock_security_group }}"
shiva_ssh_key_name: "{{ main_host_access_key }}"
shiva_aws_instance_image_id: ami-30c74e50
shiva_aws_instance_image_name: dock-ami-build-v.0.0.1
shiva_aws_instance_type: t2.medium
shiva_dock_pool_asg_name: "{{ environment }}-asg-dock-pool"
shiva_aws_launch_configuration_name: "{{ environment }}-dock-lc-0.0.1"
shiva_aws_auto_scaling_group_subnets: "{{ aws_dock_subnet }}"
shiva_aws_auto_scaling_group_max: 29
shiva_aws_auto_scaling_group_prefix: asg-{{ environment }}-
dock_registry_s3_access_key: "{{ aws_access_key_id }}"
dock_registry_s3_secret_key: "{{ aws_secret_access_key }}"

environment_name: "{{ environment }}"

consul_host_address: "{{ main_host_private_ip }}"
consul_https_port: 65202
consul_api_port: 65201

vault_hello_runnable_github_token: "{{ hello_runnable_github_token }}"
vault_aws_access_key_id: "{{ aws_access_key_id }}"
vault_aws_secret_key: "{{ aws_secret_access_key }}"
vault_aws_region: "{{ aws_region }}"
vault_port: 65240
vault_ssl_port: 65241

stop_time: 5
log_driver: syslog
log_facility: local7
app_log_dir: /docker/app-logs

pg_user: "{{ postgres_user }}"
pg_pass: "{{ postgres_password }}"
pg_host: "{{ postgres_host }}:5432"
pg_database: astral

rabbit_host_address: "{{ hostvars[groups['rabbitmq'][0]]['ansible_default_ipv4']['address'] }}"
rabbit_port: 54321

redis_host_address: "{{ hostvars[groups['redis'][0]]['ansible_default_ipv4']['address'] }}"
redis_port: 65251

swarm_master_port: 65250
swarm_host_address: "{{ hostvars[groups['swarm-manager'][0]]['ansible_default_ipv4']['address'] }}"
swarm_container_name: swarm
swarm_version: v1.2.3-0

docker_ca_path: /etc/ssl/docker/ca.pem
docker_key_path: /etc/ssl/docker/key.pem
docker_cert_path: /etc/ssl/docker/cert.pem
docker_port: 4242

mongo_port: 27017
mongo_hosts: "{% for host in groups['mongodb'] %}{{ hostvars[host]['ansible_default_ipv4']['address'] }}:{{ mongo_port }}{% if not loop.last %},{% endif %}{% endfor %}"

github_varnish_host: "{{ hostvars[groups['github-varnish'][0]]['ansible_default_ipv4']['address'] }}"
github_varnish_port: 8765
github_domain: api.github.com
is_github_enterprise: false
github_protocol: https
github_api_url: https://api.github.com

node_env: "{{ environment }}"
registry_port: 65001
max_navi_port: 65000
redis_tls_port: 65076
api_hello_runnable_github_token: "{{ hello_runnable_github_token }}"
proxy_container_image: "{{ registry_host }}/runnable/sticky-nginx"
proxy_container_image_version: v1.8.1
