api_aws_access_key_id: AKIAJZLLEJFE7KDUVVVQ
api_aws_secret_access_key: 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
api_github_client_id: ${GITHUB_CLIEND_ID}
api_github_client_secret: ${GITHUB_CLIENT_SECRET}
api_github_deploy_keys_bucket: runnable.deploykeys.hot-grizzly
api_mongo_auth: 25f39cf14e374870af2a86a12000263a:5d3159d577544f5d896bdf4ae3b14643
api_mongo_database: hot-grizzly
api_mongo_replset_name: hot-grizzly-rs0
api_s3_context_bucket: runnable.context.resources.hot-grizzly
api_hostname: api.{{ domain }}
api_url: https://{{ api_hostname }}

big_poppa_pg_pass: 7e60015444144abdbe7124813b2ac9fc
big_poppa_pg_host: big-poppa.cnksgdqarobf.us-west-2.rds.amazonaws.com:5432
big_poppa_pg_port: 5432
big_poppa_pg_user: a6c6898ffb866437
big_poppa_pg_database: big_poppa
big_poppa_github_token: 6bd3f5155255f5f5d04f2787bb05cf37dbf1e819
big_poppa_mongo_auth: 25f39cf14e374870af2a86a12000263a:5d3159d577544f5d896bdf4ae3b14643
big_poppa_mongo_database: hot-grizzly
big_poppa_mongo_replset_name: hot-grizzly-rs0
big_poppa_pg_pool_min: 10
big_poppa_pg_pool_max: 20

cream_hello_runnable_github_token: 6bd3f5155255f5f5d04f2787bb05cf37dbf1e819
cream_stripe_secret_key: sk_test_4De8Zdkfcyb29swkMmjZUMRh
cream_stripe_publishable_key: pk_test_sHr5tQaPtgwiE2cpW6dQkzi8

drake_port: 80

khronos_mongo_auth: 25f39cf14e374870af2a86a12000263a:5d3159d577544f5d896bdf4ae3b14643
khronos_mongo_database: hot-grizzly
khronos_mongo_replset_name: hot-grizzly

navi_cookie_secret: 966b064bad58465e80e6333482af77f9
navi_proxy_port: 65100
navi_proxy_ssl_port: 65101

optimus_aws_access_id: AKIAJZLLEJFE7KDUVVVQ
optimus_aws_secret_id: uYjxW3/ndlFvVxLmJvvVOBbReL8OfUbPbDjkN1RZ
optimus_github_deploy_keys_bucket: runnable.deploykeys.hot-grizzly


pheidi_mongo_auth: 25f39cf14e374870af2a86a12000263a:5d3159d577544f5d896bdf4ae3b14643
pheidi_mongo_database: hot-grizzly
pheidi_mongo_replset_name: hot-grizzly
pheidi_runnabot_tokens: 6bd3f5155255f5f5d04f2787bb05cf37dbf1e819

registry_s3_access_key: AKIAJZLLEJFE7KDUVVVQ
registry_s3_secret_key: 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
registry_s3_bucket: runnableimages.hot-grizzly
registry_s3_region: us-west-2

aws_access_key_id: AKIAJZLLEJFE7KDUVVVQ
aws_secret_access_key: AKIAJZLLEJFE7KDUVVVQ
shiva_aws_region: us-west-2
shiva_dock_security_groups: sg-ec0da194
shiva_ssh_key_name: gamma-key
shiva_aws_instance_image_id: ami-30c74e50
shiva_aws_instance_image_name: dock-ami-build-v.0.0.1
shiva_aws_instance_type: t2.medium
shiva_dock_pool_asg_name: hot-grizzly-asg-dock-pool
shiva_aws_launch_configuration_name: hot-grizzly-lc-0.0.1
shiva_aws_auto_scaling_group_subnets: subnet-9cb197f9
shiva_aws_auto_scaling_group_max: 29
shiva_aws_auto_scaling_group_prefix: asg-hot-grizzly-

aws_access_key: AKIAJZLLEJFE7KDUVVVQ
aws_secret_key: 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
environment_name: hot-grizzly

consul_host_address: "{{ hostvars[groups['consul'][0]]['ansible_default_ipv4']['address'] }}"

vault_hello_runnable_github_token: 6ea33eb0b734f3db30ed72a870a2376ff10d2274
vault_aws_access_key_id: AKIAJZLLEJFE7KDUVVVQ
vault_aws_secret_key: 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
vault_aws_region: us-west-2
vault_port: 65240
vault_ssl_port: 65241

stop_time: 5
log_driver: syslog
log_facility: local7
app_log_dir: /docker/app-logs

rabbit_password: dfaf1bd173e74f14823c63437979db0e
rabbit_username: e50d3d3e86514ca29a96b951f69a1daa
rabbit_host_address: "{{ hostvars[groups['rabbitmq'][0]]['ansible_default_ipv4']['address'] }}"
rabbit_port: 54321

redis_host_address: "{{ hostvars[groups['redis'][0]]['ansible_default_ipv4']['address'] }}"
redis_port: 65075

registry_s3_bucket: runnableimages.hot-grizzly
registry_s3_region: us-west-2

domain: runnablecloud.com
mongo_port: 27017
node_env: hot-grizzly
pg_user: a6c6898ffb866437
pg_pass: 7e60015444144abdbe7124813b2ac9fc
pg_host: big-poppa.cnksgdqarobf.us-west-2.rds.amazonaws.com:5432
pg_database: astral
registry_port: 65001
consul_https_port: 65201
swarm_master_port: 65250
user_content_domain: runnabae.com
max_navi_port: 65000
redis_port: 65075
redis_tls_port: 65076
api_hello_runnable_github_token: 6ea33eb0b734f3db30ed72a870a2376ff10d2274
vault_auth_token: 0bf58819-d4dd-3987-95c6-e98c393578da
vault_token_01: 8d86f743e6060dbbb2c199fa2eeb73377b6d3579c819773ce55db588d35ac28f01
vault_token_02: e66d688de27362bfbc4d226e823e1e5c49b540c3320c043cb0ec79aef6005a0302
vault_token_03: d5bfe5de26570a53b87a3a64c76f0d253a7d3c11cd09f46912e0cfbcdaee356903
vault_token_04: f60812ddeee41a30aae2a6c93531e7c720dfb20a905461122492c3b2b210fcfa04
vault_token_05: c5da9f8e2ac072dcaed5bec37060f4be5317ced86f519147869e75a09efe939005
github_domain: api.github.com
is_github_enterprise: false
github_protocol: https
proxy_container_image: runnable/sticky-nginx
proxy_container_image_version: v1.8.1
