name: docker-listener

container_image: "{{ registry_host }}/runnable/{{ name }}"
container_tag: "{{ git_branch }}"
repo: "git@github.com:CodeNow/{{ name }}.git"
node_version: "4.2.2"
npm_version: "2.14.7"

restart_policy: "always"

container_envs: >
  -e CONSUL_HOST={{ consul_host_address }}:{{ consul_https_port }}
  {% if datadog_host_address is defined %} -e DATADOG_HOST={{ datadog_host_address }}{% endif %}
  {% if datadog_port is defined %} -e DATADOG_PORT={{ datadog_port }}{% endif %}
  -e IMAGE_INSPECT_LIST=localhost,registry.runnable.com,runnable
  -e DOCKER_CERT_PATH=/etc/ssl/docker
  -e NODE_ENV={{ node_env }}
  -e RABBITMQ_HOSTNAME={{ rabbit_host_address }}
  -e RABBITMQ_PASSWORD={{ rabbit_password }}
  -e RABBITMQ_PORT={{ rabbit_port }}
  -e RABBITMQ_USERNAME={{ rabbit_username }}
  -e SWARM_HOST={{ swarm_host_address }}:{{ swarm_master_port }}

container_run_opts: >
  -h {{ name }}
  -d
  -v /opt/ssl/docker/{{ name }}:/etc/ssl/docker:ro
  {{ container_envs }}
