name: api-socket-server

container_image: runnable/{{ name }}
kill_container_name: "{{ name }}"

hosted_ports: [ "{{ api_port }}" ]

# for redis
redis_key: frontend:{{ api_socket_server_hostname }}
is_redis_update_required: yes

# for container settings
container_envs: >
  {{ api_base_container_envs }}
  -e NUM_WORKERS=1

container_run_opts: >
  --name {{ name }}
  -h {{ name }}
  -d
  -P
  -v /opt/ssl/docker/{{ name }}:/etc/ssl/docker:ro
  -v /opt/ssl/mongodb-client:/opt/ssl/mongodb-client:ro
  {{ container_envs }}
