name: drake-http

container_image: "{{ registry_host }}/runnable/{{ name }}"
container_tag: "{{ git_branch }}"
hosted_ports: ["{{ drake_port }}"]
repo: "git@github.com:CodeNow/drake.git"
node_version: "4.4.7"
npm_version: 2

# Exposes drake (heh)
redis_key: "frontend:{{ drake_hostname }}"
is_redis_update_required: 'yes'

# for container settings
container_envs: >
  -e API_URL={{ api_url }}
  -e DATADOG_SECRET=datadog-secret
  {% if datadog_host_address is defined %} -e DATADOG_HOST={{ datadog_host_address }}{% endif %}
  {% if datadog_port is defined %} -e DATADOG_PORT={{ datadog_port }}{% endif %}
  -e NODE_ENV={{ node_env }}
  -e PORT={{ hosted_ports[0] }}
  -e RABBITMQ_HOSTNAME={{ rabbit_host_address }}
  -e RABBITMQ_PASSWORD={{ rabbit_password }}
  -e RABBITMQ_PORT={{ rabbit_port }}
  -e RABBITMQ_USERNAME={{ rabbit_username }}
  {% if drake_http_rollbar_token is defined %} -e ROLLBAR_KEY={{ drake_http_rollbar_token }} {% endif %}

container_run_opts: >
  -h {{ name }}
  -d
  -p {{ drake_port }}
  {{container_envs}}

npm_start_command: run start-http
