name: optimus

container_image: "{{ registry_host }}/runnable/{{ name }}"
container_tag: "{{ git_branch }}"
repo: git@github.com:CodeNow/{{ name }}.git
hosted_ports: ["{{ optimus_port }}"]
node_version: "4.3.2"
npm_version: "2.8.3"

# for redis
redis_key: frontend:{{ optimus_hostname }}
is_redis_update_required: yes

container_envs: >
  -e NODE_ENV={{ node_env }}
  -e PORT={{ hosted_ports[0] }}
  -e AWS_ACCESS_KEY_ID={{ optimus_aws_access_id }}
  -e AWS_SECRET_ACCESS_KEY={{ optimus_aws_secret_id }}
  -e S3_DEPLOY_KEY_BUCKET={{ optimus_github_deploy_keys_bucket }}
  -e LOG_LEVEL=trace

container_run_opts: >
  -h {{ name }}
  -d
  -P
  {{ container_envs }}
