---
name: swarm-cloudwatch-reporter

repo: git@github.com:CodeNow/furry-cactus.git
container_image: "{{ registry_host }}/runnable/furry-cactus"
container_tag: "{{ git_branch }}"
node_version: "4.4.7"
npm_version: 3
do_not_push: true

log_driver: json-file

dockerfile_pre_install_commands:
- npm config set progress false

container_run_opts: >-
  --log-driver={{ log_driver }}
  -e AWS_ACCESS_KEY={{ aws_cloudwatch_access_key }}
  -e AWS_SECRET_KEY={{ aws_cloudwatch_secret_key }}
  -e DOCKER_CERT_PATH=/opt/ssl/docker/swarm-manager
  -e ENVIRONMENT={{ environment }}
  -e ENVIRONMENT_PREFIX=""
  -e SECURITY_GROUP_SUFFIX="dock-sg"
  -e SWARM_HOSTNAME={{ main_host_private_ip }}
  -e SWARM_PORT={{ swarm_master_port }}
  -v /opt/runnable/get-info.js:/get-info.js:ro
  -v /opt/ssl/docker/swarm-manager:/opt/ssl/docker/swarm-manager:ro
  -v /var/log:/var/log

container_run_args: npm start >> /var/log/{{ name }}.log 2>&1
