---
- name: create configuration directory
  become: yes
  file:
    path=/opt/runnable/vault
    state=directory
    recurse=yes

- name: create consul client certificate directory
  become: yes
  file:
    path=/opt/vault/client-consul
    state=directory
    recurse=yes

- name: create vault server tls certificate directory
  become: yes
  file:
    path=/opt/vault/server
    state=directory
    recurse=yes

- name: copy vault config
  tags: [ deploy ]
  become: true
  template:
    src=vault.hcl
    dest=/opt/runnable/vault/vault.hcl
