---
- hosts: rabbitmq
- hosts: consul
- hosts: mongodb
- hosts: github-varnish

- hosts: big-poppa
  vars_files:
    - group_vars/alpha-big-poppa-http.yml
  roles:
  - { role: logs }
  - { role: container_kill_start }
