---
- hosts: rabbitmq
- hosts: mongodb
- hosts: consul
- hosts: swarm-manager
- hosts: big-poppa
- hosts: khronos
  vars_files:
    - group_vars/alpha-khronos.yml
  roles:
  - { role: logs }
  - { role: khronos, tags: [ deploy ] }
  - { role: container_kill_start }
