---
- hosts: single-host-proxy
  vars_files:
    - group_vars/alpha-single-host-proxy.yml
  roles:
  - role: drake-proxy
    proxy_service_name: drake-http
  - role: content-domain-proxy
    proxy_service_name: navi
  - role: runnable-domain-proxy
    proxy_service_name: api
  - role: logs
  - role: container_kill_start
