# Docks Services
- include: swarm-manager.yml
- include: palantiri.yml git_branch="{{ palantiri_branch }}"
- include: sauron.yml git_branch="{{ sauron_branch }}"
- include: shiva.yml git_branch="{{ astral_branch }}"
- include: khronos.yml git_branch="{{ khronos_branch }}"
- include: docker-listener.yml git_branch="{{ docker_listener_branch }}"

# Proxies
- include: registrator-api.yml # Only one of these is needed, so registrator-navi is not needed
- include: single-host-proxy.yml # API depends on NGINX to be running
- include: consul-template-updater.yml
  vars:
    var_file: alpha-drake-proxy.yml
- include: consul-template-updater.yml
  vars:
    var_file: alpha-navi-proxy.yml
- include: consul-template-updater.yml
  vars:
    var_file: alpha-ingress-proxy.yml
- include: consul-template-updater.yml
  vars:
    var_file: alpha-api-socket-server-proxy.yml
- include: github-varnish.yml git_branch="{{ github_varnish_branch }}"

# Main
- include: big-poppa.yml git_branch="{{ big_poppa_branch }}"
- include: api.yml git_branch="{{ api_branch }}"
- include: drake.yml git_branch="{{ drake_branch }}"
- include: cream.yml git_branch="{{ cream_branch }}"  # CREAM fails if big-poppa or API is down
- include: web.yml git_branch="{{ runnable_angular_branch }}"

# Networking services
- include: detention.yml git_branch="{{ detention_branch }}"
- include: link.yml git_branch="{{ link_branch }}"
- include: navi.yml git_branch="{{ navi_branch }}" # Connects to Redis over tls port

# Other
- include: optimus.yml git_branch="{{ optimus_branch }}"
- include: pheidi.yml git_branch="{{ pheidi_branch }}"
- include: enterprise-signin.yml git_branch="{{ enterprise_signin_branch }}"
