---
- hosts: socket-server
  vars_files:
    - group_vars/alpha-api-base.yml
    - group_vars/alpha-socket-server.yml
  roles:
  - { role: docker_client, tags: "docker_client" }
  - { role: logs }
  - { role: container_kill_start, number_of_containers: 1 }
