---
- hosts: consul

- hosts: swarm-manager
  vars_files:
    - "group_vars/alpha-swarm-manager.yml"
  roles:
  - { role: logs }
  - { role: docker_client, tags: "docker_client" }
  - { role: container_kill_start }
