---
- hosts: swarm-manager
  vars_files:
  - group_vars/alpha-swarm-cloudwatch-reporter.yml
  tasks:
  - name: login to registry
    tags: deploy
    become: yes
    command: docker login -u {{ registry_username }} -p {{ registry_token }} {{ registry_host }}

  # get latest image
  # tag will default to latest
  - name: pull down docker image {{ container_image }}:{{ container_tag }}
    tags: deploy
    become: yes
    command: docker pull {{ container_image }}:{{ container_tag }}

  - name: logout of registry
    tags: deploy
    become: yes
    command: docker logout {{ registry_host }}

  - name: run container
    tags: test_swarm_stats
    when: test_swarm_stats is defined
    become: yes
    shell: >-
      docker run
      {{ container_run_opts }}
      {{ container_image }}:{{ container_tag }}
      {{ container_run_args }}

  - name: put script into cron
    tags: [ deploy ]
    become: yes
    cron:
      name: swarm-cloudwatch-reporter
      state: present
      minute: "*/5"
      job: >-
        docker run
        --rm
        {{ container_run_opts }}
        {{ container_image }}:{{ container_tag }}
        {{ container_run_args }}
